INSERT INTO public.mesa(
	num_numero_mesa, num_capacidad, fk_id_restaurante, fec_creacion, fec_actualizacion)
	VALUES 
    (001, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (002, 5, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (003, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (004, 6, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (005, 2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (006, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (007, 5, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (008, 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (009, 6, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (010, 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);