SELECT *
  FROM RESERVA,
       CLIENTE;
/*
CREATE TABLE MESAS_RESERVADAS (
    PK_ID_MESAS_RESERVADAS SERIAL PRIMARY KEY,
    NK_ID_MESAS_RESERVADAS INTEGER,
    DES_NOMBRE_CLIENTE CHARACTER VARYING (50), --NAME COMPLETE
    DES_TELEFONO CHARACTER VARYING (15),
    COD_RESERVA  INTEGER , --PK_ID_RESERVA
    NUM_NUMERO_MESA INTEGER ,
    NUM_CAPACIDAD_MESA INTEGER,
    DES_NOMBRE_RESTAURANTE CHARACTER VARYING (50),
    FEC_ACTUALIZACION TIMESTAMP,
    FEC_CARGA_DATOS TIMESTAMP    
);

ALTER TABLE PUBLIC.MESAS_RESERVADAS
ADD CONSTRAINT uk_mesas_reservadas UNIQUE (NK_ID_MESAS_RESERVADAS);
*/

CREATE OR REPLACE FUNCTION SP_UPATE_MESAS_RESERVADAS() RETURNS void AS $CODE$
BEGIN
TRUNCATE TABLE MESAS_RESERVADAS RESTART IDENTITY;
INSERT INTO PUBLIC.MESAS_RESERVADAS (
    NK_ID_MESAS_RESERVADAS,
    DES_NOMBRE_CLIENTE,
    DES_TELEFONO,
    COD_RESERVA,
    NUM_NUMERO_MESA,
    NUM_CAPACIDAD_MESA,
    DES_NOMBRE_RESTAURANTE,
    FEC_ACTUALIZACION,
    FEC_CARGA_DATOS
)
SELECT DISTINCT ON (NK_ID_MESAS_RESERVADAS)
      NK_ID_MESAS_RESERVADAS,
    DES_NOMBRE_CLIENTE,
    DES_TELEFONO,
    COD_RESERVA,
    NUM_NUMERO_MESA,
    NUM_CAPACIDAD_MESA,
    DES_NOMBRE_RESTAURANTE,
    CURRENT_TIMESTAMP AT TIME ZONE 'AMERICA/BOGOTA' AS FEC_ACTUALIZACION,
    CURRENT_TIMESTAMP AT TIME ZONE 'AMERICA/BOGOTA' AS FEC_CARGA_DATOS
FROM (
    SELECT CAST(C.DES_NOMBRE || ' ' || C.DES_APELLIDO AS CHARACTER VARYING) AS DES_NOMBRE_CLIENTE,
               CAST(C.PK_ID_CLIENTE AS INTEGER) AS NK_ID_MESAS_RESERVADAS,
               C.DES_TELEFONO,
               CAST(R.PK_ID_RESERVA AS INTEGER)AS COD_RESERVA,
               CAST(M.NUM_NUMERO_MESA AS INTEGER) AS NUM_NUMERO_MESA,
               CAST (M.NUM_CAPACIDAD AS INTEGER)AS NUM_CAPACIDAD_MESA,
               RE.DES_NOMBRE AS DES_NOMBRE_RESTAURANTE,
               CURRENT_TIMESTAMP AT TIME ZONE 'AMERICA/BOGOTA' AS FEC_ACTUALIZACION,
               CURRENT_TIMESTAMP AT TIME ZONE 'AMERICA/BOGOTA' AS FEC_CARGA_DATOS
          FROM CLIENTE C
         INNER JOIN RESERVA R
            ON C.PK_ID_CLIENTE = R.FK_ID_CLIENTE
         INNER JOIN MESA M
            ON M.PK_ID_MESA = R.FK_ID_MESA
         INNER JOIN RESTAURANTE RE
            ON RE.PK_ID_RESTAURANTE = M.FK_ID_RESTAURANTE
) AS ORIGEN
ON CONFLICT(NK_ID_MESAS_RESERVADAS) DO UPDATE
SET
    DES_NOMBRE_CLIENTE = EXCLUDED.DES_NOMBRE_CLIENTE,
    DES_TELEFONO = EXCLUDED.DES_TELEFONO,
    COD_RESERVA = EXCLUDED.COD_RESERVA,
    NUM_NUMERO_MESA = EXCLUDED.NUM_NUMERO_MESA,
    NUM_CAPACIDAD_MESA = EXCLUDED.NUM_CAPACIDAD_MESA,
    DES_NOMBRE_RESTAURANTE = EXCLUDED.DES_NOMBRE_RESTAURANTE,
    FEC_ACTUALIZACION = EXCLUDED.FEC_ACTUALIZACION,
    FEC_CARGA_DATOS = EXCLUDED.FEC_CARGA_DATOS;
  
END $CODE$ LANGUAGE PLPGSQL;

--SELECT * FROM MESAS_RESERVADAS
SELECT  SP_UPATE_MESAS_RESERVADAS();

--  DROP FUNCTION sp_upate_mesas_reservadas() 



 
 SELECT COUNT(*)
  FROM MESAS_RESERVADAS;
  
SELECT * FROM MESAS_RESERVADAS;
  
  
TRUNCATE MESAS_RESERVADAS CASCADE;
TRUNCATE TABLE MESAS_RESERVADAS RESTART IDENTITY;
