-- Create CLIENTE table
CREATE TABLE CLIENTE (
    PK_ID_CLIENTE SERIAL PRIMARY KEY,
    DES_NOMBRE CHARACTER VARYING(30) NOT NULL,
    DES_APELLIDO CHARACTER VARYING(30) NOT NULL,
    NUM_TELEFONO SMALLINT NULL,
    DES_EMAIL CHARACTER VARYING(30) NULL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FEC_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE CLIENTE
ALTER COLUMN NUM_TELEFONO TYPE CHARACTER VARYING(15);

ALTER TABLE CLIENTE
ALTER COLUMN DES_EMAIL TYPE CHARACTER VARYING(50);

-- renombrando el nombre de la columna
ALTER TABLE cliente
RENAME COLUMN num_telefono TO des_telefono;



-- Create RESTAURANTE table
CREATE TABLE RESTAURANTE (
    PK_ID_RESTAURANTE SERIAL PRIMARY KEY,
    DES_NOMBRE CHARACTER VARYING(20) NOT NULL,
    DES_DIRECCION CHARACTER VARYING(30) NOT NULL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FEC_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create MESA table
CREATE TABLE MESA (
    PK_ID_MESA SERIAL PRIMARY KEY,
    NUM_NUMERO_MESA SMALLINT NOT NULL,
    NUM_CAPACIDAD SMALLINT NOT NULL,
    FK_ID_RESTAURANTE SERIAL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FEC_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Add foreign key constraint to MESA table
ALTER TABLE MESA
ADD CONSTRAINT FK_MESA_RESTAURANTE
FOREIGN KEY (FK_ID_RESTAURANTE)
REFERENCES RESTAURANTE(PK_ID_RESTAURANTE);

-- Create RESERVA table
CREATE TABLE RESERVA (
    PK_ID_RESERVA SERIAL PRIMARY KEY,
    FK_ID_CLIENTE SERIAL,
    FK_ID_MESA SERIAL,
    FK_ID_RESTAURANTE SERIAL,
    FEC_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FEC_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Add foreign key constraints to RESERVA table
ALTER TABLE RESERVA
ADD CONSTRAINT FK_RESERVA_CLIENTE
FOREIGN KEY (FK_ID_CLIENTE)
REFERENCES CLIENTE(PK_ID_CLIENTE);

ALTER TABLE RESERVA
ADD CONSTRAINT FK_RESERVA_MESA
FOREIGN KEY (FK_ID_MESA)
REFERENCES MESA(PK_ID_MESA);

ALTER TABLE RESERVA
ADD CONSTRAINT FK_RESERVA_RESTAURANTE
FOREIGN KEY (FK_ID_RESTAURANTE)
REFERENCES RESTAURANTE(PK_ID_RESTAURANTE);




TRUNCATE CLIENTE, RESTAURANTE, MESA, RESERVA CASCADE;

TRUNCATE TABLE CLIENTE, RESTAURANTE, MESA, RESERVA RESTART IDENTITY;


select * from RESTAURANTE;