CREATE TABLE CONTEO_CLIENTES (
    PK_CONTEO_CLIENTES SERIAL PRIMARY KEY,
    TOTAL INTEGER,
    TIEMPO TIME WITH TIME ZONE
)

--DROP FUNCTION first_sp_cliente()
CREATE OR REPLACE FUNCTION FIRST_SP_CLIENTE() RETURNS TRIGGER LANGUAGE PLPGSQL AS $CODE$
DECLARE
    MI_VARIABLE RECORD;
    CONTADOR    INTEGER := 0;
BEGIN
    FOR MI_VARIABLE IN (
        SELECT
            *
        FROM
            CLIENTE
    ) LOOP
        CONTADOR := CONTADOR + 1;
    END LOOP;

    INSERT INTO CONTEO_CLIENTES (TOTAL, TIEMPO)
    VALUES (CONTADOR, NOW());
END;
$CODE$;

